### ISSUE TITLE
TODO on UI as of Nov 1, 2020

### ISSUE THREAD

**Issue by Sheldonfrith** [Sheldonfrith/theplaceforme-frontend#1]
- [x] add loading view for final results page
- [x] improve 'info' popups in the questionaire.
- [x] add links to methodology, and source-links/descriptions/comments etc. for each dataset somewhere in the questionaire
- [x] improve the colors (more yellow hue? gradients?)
- [x] test and improve the ui on mobile
- [x] Range sliders in questionaire: -make it so they consistently have around 100 'postions' available no matter the actual number range they are representing
- [x] add margin at bottom of questionaire
- [x] add a consistent click and hover animation to all buttons and interactable elements
- [x] modernize the look of the 'results' divs in results page, especially the colors/gradients, add border radius, 
- [x] make bottom buttons in results page look better/ more consisntent with the rest of the app
- [x] add some sort of border around the results-area div
- [x] full-page-popupus: make it so the menu button doesn't peek over the top of the popup (potentially add blur to the background?)
- [x] detailed results popup: improve the wiki button and map in wide-screen views
- [ ] improve the google maps display by altering the default zoom based on the size of each country, and also putting a little marker on the map to mark the country if they lose it. 
- [x] widen the detailed results popup content area
- [x] improve the formatting and look of the Per-Dataset Details tables
- [ ] add pie chart to show the category breakdown
- [ ] style the ads, provide mock-examples for the detailed results and general results areas
- [x] remove or improve the 'provider' info field in the account popup
- [x] improve the formatting in the account popup
- [ ] implement a custom alert popup, instead of the browser default, for things like reseting the questionaire
- [ ] implement an error page or popup of some sort
- [x] improve formatting of the 'change question defaults' popup
- [x] on large screens change the > and < buttons to text ('next question', etc.)
- [x] Add a logo graphic
- [x] Add a background photo for the margins on wide screens
- [ ] Improve landing page, probably add a photo/video, improve bottom buttons
- [x] Add By Sheldon Frith with a link to my website to the header on all pages.

-

**Comment by Sheldonfrith** [comment]
- [x] when moving to a different question the scroll position should be reset to the top of the question each time
